version: "2"
services:
  project:
    container_name: project
    image: rails-for-webpacker
    command: rails server -b 0.0.0.0
    environment:
      DATABASE_URL: "mysql2://root:11111111@mysql/project"
    volumes:
       - "./project:/workdir"
    ports:
      - "3000:3000"
  mysql:
    container_name: mysql
    image: "mysql:5.6"
    environment:
      MYSQL_ROOT_PASSWORD: 11111111
      MYSQL_DATABASE: project
    volumes:
       - /var/lib/mysql/data
